import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div>
        <Link href={'/todo'}>ToDo Page</Link>
        <Link href={'/todo/1'}>ToDo 1 Page</Link>
        <Link href={'/todo/2'}>ToDo 2 Page</Link>
        <Link href={'/todo/3'}>ToDo 3 Page</Link>
      </div>
      {children}</body>
    </html>
  )
}
